### ISSUE TITLE
CSS / Menu bug - wrapping entry in menu

### ISSUE THREAD

**Issue by 6footgeek** [daftspaniel/np8080#53]
As screenshot shows, there is a double lined entry in the menu.
Tested @ 1080p and 1440p.
Tested in Chrome.

![screen shot 2017-10-19 at 09 10 48](https://user-images.githubusercontent.com/6115480/31760722-86526706-b4ad-11e7-8b37-6228f93f7945.png)

**Comment by daftspaniel** [comment]
Could not recreate but have reduced menu padding so hopefully fixed.
